model = "gpt-5.2-codex"
model_reasoning_effort = "medium"

sandbox_mode = "workspace-write"
approval_policy = "on-request"

file-opener = "vscode"

[profiles.yolo]
sandbox_mode = "danger-full-access"
approval_policy = "never"

[sandbox_danger_full_access]
network_access = true

[features]
web_search_request = true
rmcp_client = true

[history]
persistence = "save-all"
max_bytes = 52428800 # 50 MiB

[mcp_servers.playwright]
command = "npx"
args = ["@playwright/mcp@latest"]
